//! LLM AGENT SWARM: end-to-end test of the partitioned context engine
//! through the real MCP HTTP surface.
//!
//! ~50 agents, each seeded with organizational memories generated by a
//! cheap/free LLM on OpenRouter (one batched completion per agent,
//! spread across several models so free-tier rate limits cannot flake
//! the run; `--offline` substitutes deterministic canned content).
//! The agents then write and read SIMULTANEOUSLY through `tools/call`:
//!
//! - `openmemory_remember` per memory, asserting an
//!   `{accepted, durable}` engine receipt;
//! - an immediate `openmemory_recall` for a unique per-memory marker
//!   token — the durable-ack read-your-writes guarantee, hard-asserted;
//! - interleaved cross-agent recalls and `openmemory_status` calls.
//!
//! Hard invariants (non-zero exit on violation): every MCP call
//! succeeds, every receipt is accepted+durable, every read-your-writes
//! probe hits, the store ends with EXACTLY the accepted observation
//! count, zero tombstones, zero engine write errors, and a sample of
//! markers recalls globally after the storm. Then the profile is
//! migrated to a different domain count (`--migrate-to`, 0 skips) and
//! the same sample must still recall — the full feature surface under
//! one run.
//!
//! Run (offline):  cargo run --release -p openmemory-mcp --features mcp-http --example swarm -- --offline
//! Run (live LLM): OPENROUTER_API_KEY=... cargo run --release -p openmemory-mcp --features mcp-http --example swarm

use std::collections::HashMap;
use std::sync::atomic::{AtomicU64, AtomicUsize, Ordering};
use std::sync::{Arc, Barrier, Mutex};
use std::time::{Duration, Instant};

use clap::Parser;
use openmemory_engine::partition::DomainStore;
use serde_json::{json, Value};

mod common;
use common::{pctl, McpClient, TestServer};

#[derive(Parser, Debug, Clone)]
#[command(name = "swarm", about = "LLM agent swarm over the MCP HTTP surface")]
struct Args {
    /// Concurrent agents (each is one OS thread).
    #[arg(long, default_value_t = 50)]
    agents: usize,
    /// Memories each agent writes.
    #[arg(long, default_value_t = 8)]
    memories: usize,
    /// Storage domains for the profile under test.
    #[arg(long, default_value_t = 4)]
    domains: usize,
    /// Engine shards (must be a multiple of domains).
    #[arg(long, default_value_t = 32)]
    shards: usize,
    /// Comma-separated OpenRouter model ids. Free-tier models rotate
    /// round-robin so per-model rate limits spread out.
    #[arg(
        long,
        default_value = "meta-llama/llama-3.3-70b-instruct:free,openai/gpt-oss-20b:free,qwen/qwen3-next-80b-a3b-instruct:free,nvidia/nemotron-nano-9b-v2:free,meta-llama/llama-3.2-3b-instruct:free"
    )]
    models: String,
    /// Concurrent LLM requests during content generation.
    #[arg(long, default_value_t = 6)]
    llm_concurrency: usize,
    /// Skip the LLM and use deterministic canned content.
    #[arg(long, default_value_t = false)]
    offline: bool,
    /// Migrate the populated profile to this domain count afterwards
    /// (0 skips the migration phase).
    #[arg(long, default_value_t = 2)]
    migrate_to: usize,
    /// Markers re-validated globally after the storm and again after
    /// migration.
    #[arg(long, default_value_t = 100)]
    sample: usize,
}

const TEAMS: [&str; 10] = [
    "payments",
    "infra",
    "mobile",
    "search",
    "data-platform",
    "identity",
    "growth",
    "support-tools",
    "ml-serving",
    "security",
];

/// One memory an agent will write. The marker is appended client-side
/// so read-your-writes validation never depends on LLM compliance.
#[derive(Debug, Clone)]
struct MemoryItem {
    entity: String,
    entity_type: String,
    observation: String,
    /// Optional relation to the agent's team entity — exercises the
    /// cross-domain stub/mirror path under concurrency.
    relate_to_team: bool,
}

/// Unique, FTS-tokenizable marker for agent `a`, memory `m`.
fn marker(agent: usize, memory: usize) -> String {
    format!("swarmtoken{agent:02}x{memory:02}")
}

fn canned_memories(agent: usize, team: &str, count: usize) -> Vec<MemoryItem> {
    let kinds = ["decision", "incident", "milestone", "ownership"];
    (0..count)
        .map(|m| {
            let kind = kinds[m % kinds.len()];
            MemoryItem {
                entity: format!("{team}-{kind}-{agent:02}-{m:02}"),
                entity_type: if m % 3 == 0 { "event" } else { "fact" }.into(),
                observation: format!(
                    "the {team} team recorded {kind} number {m}: rollout proceeds \
                     after the quarterly review confirmed capacity"
                ),
                relate_to_team: m % 3 == 1,
            }
        })
        .collect()
}

// ---------------------------------------------------------------------------
// OpenRouter content generation
// ---------------------------------------------------------------------------

#[derive(Default)]
struct LlmStats {
    calls: AtomicUsize,
    retries: AtomicUsize,
    fallbacks: AtomicUsize,
    prompt_tokens: AtomicU64,
    completion_tokens: AtomicU64,
}

fn llm_prompt(team: &str, count: usize) -> String {
    format!(
        "You are an engineer on the {team} team writing entries into your \
         organisation's shared memory. Produce exactly {count} distinct, \
         realistic entries as a STRICT JSON array (no markdown, no prose). \
         Each element: {{\"entity\": short name of the project/person/system \
         the fact is about, \"entity_type\": one of \"project\"|\"person\"|\
         \"fact\"|\"event\"|\"tool\", \"observation\": one or two concrete \
         sentences (a decision, incident detail, ownership change, or \
         deadline)}}. Vary the entities. Output ONLY the JSON array."
    )
}

/// One chat completion against OpenRouter, with bounded retries on
/// rate limits and transient failures. Returns the content string.
fn openrouter_chat(api_key: &str, model: &str, prompt: &str, stats: &LlmStats) -> Option<String> {
    let body = json!({
        "model": model,
        "messages": [{"role": "user", "content": prompt}],
        "max_tokens": 1200,
        "temperature": 0.8,
    });
    for (attempt, backoff_secs) in [0u64, 3, 8, 15].iter().enumerate() {
        if *backoff_secs > 0 {
            std::thread::park_timeout(Duration::from_secs(*backoff_secs));
        }
        if attempt > 0 {
            stats.retries.fetch_add(1, Ordering::Relaxed);
        }
        stats.calls.fetch_add(1, Ordering::Relaxed);
        let response = ureq::post("https://openrouter.ai/api/v1/chat/completions")
            .set("Authorization", &format!("Bearer {api_key}"))
            .set("HTTP-Referer", "https://github.com/raymondj99/openmemory")
            .set("X-Title", "openmemory swarm test")
            .timeout(Duration::from_secs(90))
            .send_json(body.clone());
        match response {
            Ok(resp) => {
                let parsed: Value = match resp.into_json() {
                    Ok(v) => v,
                    Err(_) => continue,
                };
                if let Some(usage) = parsed.get("usage") {
                    stats.prompt_tokens.fetch_add(
                        usage
                            .get("prompt_tokens")
                            .and_then(Value::as_u64)
                            .unwrap_or(0),
                        Ordering::Relaxed,
                    );
                    stats.completion_tokens.fetch_add(
                        usage
                            .get("completion_tokens")
                            .and_then(Value::as_u64)
                            .unwrap_or(0),
                        Ordering::Relaxed,
                    );
                }
                if let Some(content) = parsed["choices"][0]["message"]["content"].as_str() {
                    if !content.trim().is_empty() {
                        return Some(content.to_string());
                    }
                }
            }
            // 429 / 5xx: retry after backoff; anything else: next attempt
            // anyway (free endpoints are erratic), bounded by the loop.
            Err(_) => {}
        }
    }
    None
}

/// Lenient JSON-array extraction: free models love markdown fences.
fn parse_llm_memories(
    raw: &str,
    team: &str,
    agent: usize,
    count: usize,
) -> Option<Vec<MemoryItem>> {
    let start = raw.find('[')?;
    let end = raw.rfind(']')?;
    let parsed: Value = serde_json::from_str(raw.get(start..=end)?).ok()?;
    let array = parsed.as_array()?;
    let mut out = Vec::new();
    for (m, item) in array.iter().take(count).enumerate() {
        let entity = item["entity"]
            .as_str()
            .unwrap_or_default()
            .trim()
            .to_string();
        let observation = item["observation"]
            .as_str()
            .unwrap_or_default()
            .trim()
            .to_string();
        if entity.is_empty() || observation.is_empty() {
            continue;
        }
        let entity_type = match item["entity_type"].as_str().unwrap_or("fact") {
            t @ ("project" | "person" | "fact" | "event" | "tool" | "concept") => t,
            _ => "fact",
        };
        out.push(MemoryItem {
            entity: entity.chars().take(120).collect(),
            entity_type: entity_type.to_string(),
            observation: observation.chars().take(800).collect(),
            relate_to_team: m % 3 == 1,
        });
    }
    // Pad with canned items if the model under-delivered.
    if out.len() < count {
        let pad = canned_memories(agent, team, count);
        out.extend(pad.into_iter().skip(out.len()));
    }
    (!out.is_empty()).then_some(out)
}

/// Generate every agent's memories up front: one LLM call per agent,
/// `llm_concurrency` in flight, models rotating round-robin, canned
/// fallback on persistent failure. The swarm itself then runs at full
/// concurrency without being throttled by free-tier limits.
fn generate_content(args: &Args, api_key: Option<&str>) -> (Vec<Vec<MemoryItem>>, LlmStats) {
    let stats = LlmStats::default();
    let mut content: Vec<Vec<MemoryItem>> = (0..args.agents)
        .map(|a| canned_memories(a, TEAMS[a % TEAMS.len()], args.memories))
        .collect();

    let Some(api_key) = api_key else {
        return (content, stats);
    };
    let models: Vec<String> = args
        .models
        .split(',')
        .map(|m| m.trim().to_string())
        .filter(|m| !m.is_empty())
        .collect();

    let next = AtomicUsize::new(0);
    let results: Mutex<HashMap<usize, Vec<MemoryItem>>> = Mutex::new(HashMap::new());
    std::thread::scope(|scope| {
        for _ in 0..args.llm_concurrency.max(1) {
            scope.spawn(|| loop {
                let agent = next.fetch_add(1, Ordering::Relaxed);
                if agent >= args.agents {
                    return;
                }
                let team = TEAMS[agent % TEAMS.len()];
                let model = &models[agent % models.len()];
                let generated =
                    openrouter_chat(api_key, model, &llm_prompt(team, args.memories), &stats)
                        .and_then(|raw| parse_llm_memories(&raw, team, agent, args.memories));
                match generated {
                    Some(memories) => {
                        results.lock().unwrap().insert(agent, memories);
                    }
                    None => {
                        stats.fallbacks.fetch_add(1, Ordering::Relaxed);
                    }
                }
            });
        }
    });
    for (agent, memories) in results.into_inner().unwrap() {
        content[agent] = memories;
    }
    (content, stats)
}

#[derive(Default)]
struct SwarmStats {
    remembers: AtomicUsize,
    relations_sent: AtomicUsize,
    ryw_failures: AtomicUsize,
    receipt_failures: AtomicUsize,
    call_errors: AtomicUsize,
    cross_reads: AtomicUsize,
    cross_hits: AtomicUsize,
    status_calls: AtomicUsize,
    remember_ns: Mutex<Vec<u64>>,
    recall_ns: Mutex<Vec<u64>>,
    errors: Mutex<Vec<String>>,
}

#[allow(clippy::too_many_lines)]
fn run_agent(agent: usize, client: &McpClient, memories: &[MemoryItem], stats: &SwarmStats) {
    let team = TEAMS[agent % TEAMS.len()];
    let mut remember_ns = Vec::with_capacity(memories.len());
    let mut recall_ns = Vec::with_capacity(memories.len() * 2);
    let fail = |bucket: &AtomicUsize, message: String| {
        bucket.fetch_add(1, Ordering::Relaxed);
        let mut errors = stats.errors.lock().unwrap();
        if errors.len() < 20 {
            errors.push(message);
        }
    };

    for (m, item) in memories.iter().enumerate() {
        let mark = marker(agent, m);
        let observation = format!("{} [{mark}]", item.observation);
        let mut arguments = json!({
            "entity": item.entity,
            "entity_type": item.entity_type,
            "observations": [observation],
            "source": format!("swarm:agent-{agent:02}"),
        });
        if item.relate_to_team {
            arguments["relations"] = json!([{
                "relation_type": "belongs_to",
                "to_entity": format!("{team} team"),
                "to_entity_type": "organization",
            }]);
            stats.relations_sent.fetch_add(1, Ordering::Relaxed);
        }

        // Write, asserting the engine receipt.
        let t0 = Instant::now();
        match client.call("openmemory_remember", arguments) {
            Ok(receipt) => {
                remember_ns.push(t0.elapsed().as_nanos() as u64);
                stats.remembers.fetch_add(1, Ordering::Relaxed);
                if receipt["accepted"] != json!(true) || receipt["durable"] != json!(true) {
                    fail(
                        &stats.receipt_failures,
                        format!("agent {agent}: bad receipt: {receipt}"),
                    );
                }
            }
            Err(e) => {
                fail(&stats.call_errors, format!("agent {agent}: {e}"));
                continue;
            }
        }

        // Read-your-writes: the durable ack guarantees the marker is
        // findable the instant remember returns.
        let t0 = Instant::now();
        match client.call(
            "openmemory_recall",
            json!({"query": mark, "limit": 5, "mode": "keyword"}),
        ) {
            Ok(payload) => {
                recall_ns.push(t0.elapsed().as_nanos() as u64);
                if !payload.to_string().contains(&mark) {
                    fail(
                        &stats.ryw_failures,
                        format!("agent {agent}: marker {mark} not recalled post-ack"),
                    );
                }
            }
            Err(e) => fail(&stats.call_errors, format!("agent {agent}: {e}")),
        }

        // Cross-agent read: another team's vocabulary (soft metric —
        // whether it hits depends on swarm timing).
        if m % 2 == 1 {
            let other = TEAMS[(agent + m) % TEAMS.len()];
            let t0 = Instant::now();
            match client.call(
                "openmemory_recall",
                json!({"query": format!("{other} team"), "limit": 5}),
            ) {
                Ok(payload) => {
                    recall_ns.push(t0.elapsed().as_nanos() as u64);
                    stats.cross_reads.fetch_add(1, Ordering::Relaxed);
                    if payload["results"].as_array().is_some_and(|r| !r.is_empty()) {
                        stats.cross_hits.fetch_add(1, Ordering::Relaxed);
                    }
                }
                Err(e) => fail(&stats.call_errors, format!("agent {agent}: {e}")),
            }
        }

        // Occasional status read (aggregation surface under load).
        if m == memories.len() / 2 {
            match client.call("openmemory_status", json!({})) {
                Ok(_) => {
                    stats.status_calls.fetch_add(1, Ordering::Relaxed);
                }
                Err(e) => fail(&stats.call_errors, format!("agent {agent}: {e}")),
            }
        }
    }

    stats.remember_ns.lock().unwrap().extend(remember_ns);
    stats.recall_ns.lock().unwrap().extend(recall_ns);
}

fn validate_sample(
    label: &str,
    store: &DomainStore,
    samples: &[(usize, usize)],
    failures: &mut Vec<String>,
) {
    use openmemory_graph::recall::RecallFilters;
    let mut filters = RecallFilters::new();
    filters.mode = Some(openmemory_graph::SearchMode::KeywordOnly);
    for &(agent, memory) in samples {
        let mark = marker(agent, memory);
        let hit = store
            .recall(&mark, 5, &filters)
            .ok()
            .is_some_and(|results| {
                results
                    .iter()
                    .any(|r| r.observation.content.contains(&mark))
            });
        if !hit {
            failures.push(format!("{label}: marker {mark} unrecallable"));
        }
    }
}

#[allow(clippy::too_many_lines)]
fn main() {
    let args = Args::parse();
    let api_key = if args.offline {
        None
    } else {
        std::env::var("OPENROUTER_API_KEY")
            .ok()
            .filter(|k| !k.is_empty())
    };
    if api_key.is_none() && !args.offline {
        eprintln!("OPENROUTER_API_KEY is not set; falling back to --offline content");
    }

    // ---- Profile + in-process MCP HTTP server ------------------------------
    let server = TestServer::start(args.domains, args.shards);
    let base = server.base.clone();

    // ---- Phase A: content -------------------------------------------------
    println!(
        "swarm: {} agents x {} memories, {} domains, {} shards, content: {}",
        args.agents,
        args.memories,
        args.domains,
        args.shards,
        if api_key.is_some() {
            "OpenRouter free models"
        } else {
            "offline canned"
        }
    );
    let t0 = Instant::now();
    let (content, llm_stats) = generate_content(&args, api_key.as_deref());
    if api_key.is_some() {
        println!(
            "content generated in {:.1?}: {} llm calls, {} retries, {} fallbacks, {} prompt + {} completion tokens",
            t0.elapsed(),
            llm_stats.calls.load(Ordering::Relaxed),
            llm_stats.retries.load(Ordering::Relaxed),
            llm_stats.fallbacks.load(Ordering::Relaxed),
            llm_stats.prompt_tokens.load(Ordering::Relaxed),
            llm_stats.completion_tokens.load(Ordering::Relaxed),
        );
    }

    // ---- Phase B: simultaneous read/write storm ---------------------------
    let stats = Arc::new(SwarmStats::default());
    let barrier = Arc::new(Barrier::new(args.agents + 1));
    let handles: Vec<_> = (0..args.agents)
        .map(|agent| {
            let stats = Arc::clone(&stats);
            let barrier = Arc::clone(&barrier);
            let memories = content[agent].clone();
            let url = base.clone();
            std::thread::Builder::new()
                .name(format!("swarm-agent-{agent:02}"))
                .spawn(move || {
                    let client = McpClient::new(url);
                    barrier.wait();
                    run_agent(agent, &client, &memories, &stats);
                })
                .expect("spawn agent")
        })
        .collect();
    barrier.wait();
    let t0 = Instant::now();
    for handle in handles {
        handle.join().expect("agent thread");
    }
    let storm = t0.elapsed();

    // ---- Validation -------------------------------------------------------
    let mut failures: Vec<String> = Vec::new();
    let remembers = stats.remembers.load(Ordering::Relaxed);
    let relations_sent = stats.relations_sent.load(Ordering::Relaxed);

    for (count, what) in [
        (stats.call_errors.load(Ordering::Relaxed), "MCP call errors"),
        (
            stats.receipt_failures.load(Ordering::Relaxed),
            "bad engine receipts",
        ),
        (
            stats.ryw_failures.load(Ordering::Relaxed),
            "read-your-writes misses",
        ),
    ] {
        if count > 0 {
            failures.push(format!("{count} {what}"));
        }
    }

    let status = server.domains.status().expect("status");
    if status.total_observations != remembers as u64 {
        failures.push(format!(
            "observation count mismatch: store {} != accepted {remembers}",
            status.total_observations
        ));
    }
    if status.tombstoned_observations != 0 {
        failures.push(format!(
            "{} unexpected tombstones",
            status.tombstoned_observations
        ));
    }
    if (status.total_relations as usize) < relations_sent {
        failures.push(format!(
            "relation count {} below sent {relations_sent} (mirrors must not double-count)",
            status.total_relations
        ));
    }
    let engine_stats = server.engine.stats();
    if engine_stats.write_errors.load(Ordering::Relaxed) != 0 {
        failures.push(format!(
            "{} engine write errors",
            engine_stats.write_errors.load(Ordering::Relaxed)
        ));
    }

    // Global sample of markers, recalled through the facade.
    let samples: Vec<(usize, usize)> = (0..args.sample)
        .map(|i| ((i * 7) % args.agents, (i * 3) % args.memories))
        .collect();
    validate_sample("post-storm", &server.domains, &samples, &mut failures);

    // ---- Report -----------------------------------------------------------
    let mut remember_ns = stats.remember_ns.lock().unwrap().clone();
    remember_ns.sort_unstable();
    let mut recall_ns = stats.recall_ns.lock().unwrap().clone();
    recall_ns.sort_unstable();
    let total_ops = remember_ns.len() + recall_ns.len();
    println!(
        "\n=== swarm storm ({} agents simultaneous) ===",
        args.agents
    );
    println!(
        "  wall            : {storm:.2?}  ({:.0} MCP ops/s)",
        total_ops as f64 / storm.as_secs_f64()
    );
    println!(
        "  remembers       : {remembers} ({} with relations)  p50 {:.2?}  p99 {:.2?}",
        relations_sent,
        pctl(&remember_ns, 0.50),
        pctl(&remember_ns, 0.99),
    );
    println!(
        "  recalls         : {} (incl {} cross-agent, {:.0}% hit)  p50 {:.2?}  p99 {:.2?}",
        recall_ns.len(),
        stats.cross_reads.load(Ordering::Relaxed),
        100.0 * stats.cross_hits.load(Ordering::Relaxed) as f64
            / stats.cross_reads.load(Ordering::Relaxed).max(1) as f64,
        pctl(&recall_ns, 0.50),
        pctl(&recall_ns, 0.99),
    );
    println!(
        "  store           : {} entities, {} observations, {} relations",
        status.total_entities, status.total_observations, status.total_relations
    );

    // ---- Phase C: migrate the populated profile ---------------------------
    if args.migrate_to > 0 && args.migrate_to != args.domains {
        // Release every handle and drain the engine (journals must be
        // empty for migration preconditions to hold). The returned
        // handle keeps the profile on disk.
        let profile = server.shutdown();
        let (config, data_dir) = (&profile.config, profile.data_dir.clone());

        let t0 = Instant::now();
        match openmemory_engine::migrate::migrate_domains(config, &data_dir, args.migrate_to) {
            Ok(report) => {
                println!(
                    "\n=== migration {} -> {} domains ({:.2?}) ===",
                    report.from_domains,
                    report.to_domains,
                    t0.elapsed()
                );
                println!(
                    "  moved           : {} entities, {} observations, {} relations, {} index entries",
                    report.entities, report.observations, report.relations, report.index_entries
                );
                println!(
                    "  bookkeeping     : stubs {}->{}, mirrors {}->{}",
                    report.stubs_dropped,
                    report.stubs_created,
                    report.mirrors_dropped,
                    report.mirrors_created
                );
                let migrated =
                    DomainStore::open_existing(config, &data_dir).expect("open migrated profile");
                let after = migrated.status().expect("status after migration");
                if after.total_observations != status.total_observations
                    || after.total_relations != status.total_relations
                    || after.total_entities != status.total_entities
                {
                    failures.push(format!(
                        "post-migration status drift: {after:?} vs pre {status:?}"
                    ));
                }
                validate_sample("post-migration", &migrated, &samples, &mut failures);
            }
            Err(e) => failures.push(format!("migration failed: {e}")),
        }
    } else {
        let _ = server.shutdown();
    }

    // ---- Verdict ----------------------------------------------------------
    if failures.is_empty() {
        println!(
            "\nPASS: every invariant held ({} markers validated twice)",
            samples.len()
        );
    } else {
        println!("\nFAIL:");
        for failure in &failures {
            println!("  - {failure}");
        }
        for error in stats.errors.lock().unwrap().iter() {
            println!("  sample error: {error}");
        }
        std::process::exit(1);
    }
}
